Revert "Make libutils test compile on the host"
Fails mac build: "system/core/include/utils/Looper.h:25:10: fatal error: 'sys/epoll.h' file not found"

This reverts commit af21873e0759bf8deb0f0ea035ce2eb57b0d6f9a.

Change-Id: Ib558b8f5a303b55ab32a399d338d8aac0fae32b2