Revert "fs_mgr: correct warning on unused function parameter"
The build is broken.

system/core/fs_mgr/fs_mgr.c:824:77: error: expected '(' before 'unused'
                      const char *blk_device, long long length  __attribute__(unused))
                                                                             ^
system/core/fs_mgr/fs_mgr.c: In function 'fs_mgr_add_entry':
system/core/fs_mgr/fs_mgr.c:824:56: warning: unused parameter 'length' [-Wunused-parameter]
                      const char *blk_device, long long length  __attribute__(unused))
                                                        ^
make: *** [out/target/product/generic_x86/obj/STATIC_LIBRARIES/libfs_mgr_intermediates/fs_mgr.o] Error 1
make: *** Waiting for unfinished jobs....
This reverts commit 21095d0cae64c70b4ac7e90af7a6787019cc317a.

Change-Id: I64f8c4d9c17c0e3bbf2eb427a2c0b81bbe66ec3a