Revert "Remove String16::remove."
Reason:
frameworks/base still needs this function.

Mot-CRs-fixed:(CR)

+++
frameworks/base/tools/aapt/pseudolocalize.cpp:197:16: error: no member named 'remove' in 'android::String16'
        result.remove(length + ext, 0);
+++

This reverts commit 2cf04119102753e92b5dc09cd3820f5f15d4022f.

Change-Id: I4bbe565994c66fdf50ba7f60ed9b5411c95aa601
Reviewed-on: https://gerrit.mot.com/1979705
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Huosheng Liao <liaohs@motorola.com>
Tested-by: Jira Key
Submit-Approved: Lianlu Chen <chenll4@lenovo.com>