Revert "adb: add transport benchmark."
This reverts commit ce7ef8f89c5cd4818cbb480c3e1a3715b27393d9.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293