Fix build of adb with .9.
Without this patch we get:

system/core/adb/commandline.c:1629:16: error: array subscript is above
array bounds [-Werror=array-bounds]

Signed-off-by: Alexander Ivchenko <alexander.ivchenko@intel.com>

(cherry picked from commit 53723338858772a0189aa3f92f4d4bbdaa9b6772)

Change-Id: I920c1de933ce5ba0a0d57eb8a9b557325a767a2a