Revert "adb: add transport benchmark."
This reverts commit 4ccb61029c1c8f2484b1c8d3cf7397a88e8802eb.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293