Revert "adb: add transport benchmark."
This reverts commit 7c77a5fcc2b3495675c99ffcc28c49ccaa73e243.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293